### ISSUE TITLE
Centering (.picture img)

### ISSUE THREAD

**Issue by ChristopherJohnson25** [ChristopherJohnson25/shylock_lab#5] opened 2015-11-04 18:53 UTC
https://github.com/ChristopherJohnson25/shylock_lab/blob/master/style.css

Having a few troubles centering the (.picture img) class. I'd like it to be both horizontally and vertically centered within its div. Any suggestions?
![screen shot 2015-11-04 at 1 54 04 pm](https://cloud.githubusercontent.com/assets/15021119/10948425/8a378e2c-82fb-11e5-8312-6399bc345922.png)

**Comment by phlco** [comment] 2015-11-04 18:58
Duplicate of #5

**Closed as completed by phlco** 2015-11-04 18:58 UTC
